/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.ArrayList;

/**
 *
 * @author elois
 */
public class FenetreQuizz extends javax.swing.JFrame {
    private ArrayList<Question> listeQuestions;
    private int indexQuestionCourante = 0;
    private int score = 0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuizz.class.getName());
    
    public FenetreQuizz() {
        initComponents();
        initialiserQuestions();
        afficherQuestionCourante();
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        lblFeedback = new javax.swing.JLabel();
        QuestionSuivante = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQuestion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuestion.setForeground(new java.awt.Color(51, 51, 255));
        lblQuestion.setText("QUESTION");

        btnRep1.setText("Réponse 1");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });

        btnRep2.setText("Réponse 2");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });

        btnRep3.setText("Réponse 3");
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3ActionPerformed(evt);
            }
        });

        btnRep4.setText("Réponse 4");
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4ActionPerformed(evt);
            }
        });

        lblFeedback.setText("Réponse");

        QuestionSuivante.setText("Question Suivante");
        QuestionSuivante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionSuivanteActionPerformed(evt);
            }
        });

        lblScore.setText("Score");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QuestionSuivante)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRep1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRep2)
                        .addGap(12, 12, 12)
                        .addComponent(btnRep3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRep4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(lblQuestion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(lblFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblQuestion)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRep1)
                    .addComponent(btnRep2)
                    .addComponent(btnRep3)
                    .addComponent(btnRep4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(lblFeedback)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuestionSuivante)
                    .addComponent(lblScore))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed
    verifierReponse(1);
    }//GEN-LAST:event_btnRep1ActionPerformed

    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed
    verifierReponse (2);    // TODO add your handling code here:
    }//GEN-LAST:event_btnRep2ActionPerformed

    private void btnRep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3ActionPerformed
    verifierReponse (3);  // TODO add your handling code here:
    }//GEN-LAST:event_btnRep3ActionPerformed

    private void btnRep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4ActionPerformed
    verifierReponse (4);   // TODO add your handling code here:
    }//GEN-LAST:event_btnRep4ActionPerformed

    private void QuestionSuivanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionSuivanteActionPerformed
    indexQuestionCourante++;
        if (indexQuestionCourante < listeQuestions.size()) {
            afficherQuestionCourante();
        } else {
            lblQuestion.setText("FIN DU QUIZ !");
            lblFeedback.setText("Quiz terminé. Score final : " + score + " / " + listeQuestions.size());
            QuestionSuivante.setEnabled(false);
            lblScore.setText("Score final : " + score + " / " + listeQuestions.size());
        }
    }//GEN-LAST:event_QuestionSuivanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuizz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QuestionSuivante;
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables

private void initialiserQuestions() {
        listeQuestions = new ArrayList<>();
       
        listeQuestions.add(new Question(
    "Quel animal est réputé pour dormir 20 heures par jour ?",
    "Le paresseux", "Le chat", "Le professeur de maths", "Le koala", 4));

        listeQuestions.add(new Question(
    "Quel fruit tombe sur la tête de Newton selon la légende ?",
    "Une banane", "Une pomme", "Une noix de coco", "Une pastèque (aie)", 2));

        listeQuestions.add(new Question(
    "Quel pays est célèbre pour avoir créé les spaghettis ?",
    "L’Italie", "La Chine", "La France (évidemment)", "Le McDo du coin", 2));

        listeQuestions.add(new Question(
    "Quel est l’animal terrestre le plus rapide ?",
    "Le guépard", "Le pigeon en ville", "Le facteur en retard", "Le lion", 1));

        listeQuestions.add(new Question(
    "Que fait une poule quand elle n’a plus de plumes ?",
    "Elle met un pull", "Elle grelotte", "Elle devient un nugget", "Elle vole enfin", 3));

        listeQuestions.add(new Question(
    "Quel est l’aliment préféré des Minions ?",
    "Les pommes", "Les steaks", "Les bananes", "Les brocolis", 3));

        listeQuestions.add(new Question(
    "Quel animal adore le miel dans les dessins animés ?",
    "Le dauphin", "L’abeille (logique)", "L’ours", "Le lama", 3));

        listeQuestions.add(new Question(
    "Quel héros vit dans une ananas sous la mer ?",
    "Ariel la petite sirène", "Bob l’éponge", "Nemo", "Aquaman", 2));

        listeQuestions.add(new Question(
    "Comment dit-on 'bonjour' en langage internet ?",
    "LOL", "PTDR", "SALUT MDR", "Bonjour… comme tout le monde", 4));

        listeQuestions.add(new Question(
    "Quelle est la spécialité du Père Noël ?",
    "Livraison express", "Vol en traîneau", "Cookies gratuits", "Tout ce qui précède", 4));
    }
   
    private void afficherQuestionCourante() {
        if (indexQuestionCourante >= listeQuestions.size()) {
            return;
        }
       
        Question question = listeQuestions.get(indexQuestionCourante);
       
        lblQuestion.setText(question.getIntitule());
       
        btnRep1.setText(question.getProposition1());
        btnRep2.setText(question.getProposition2());
        btnRep3.setText(question.getProposition3());
        btnRep4.setText(question.getProposition4());
       
        btnRep1.setEnabled(true);
        btnRep2.setEnabled(true);
        btnRep3.setEnabled(true);
        btnRep4.setEnabled(true);
       
        QuestionSuivante.setEnabled(false);
       
        lblFeedback.setText("Choisissez une réponse...");
        lblScore.setText("Score : " + score + " / " + listeQuestions.size());
    }
    
     private void verifierReponse(int reponseChoisie) {
        Question questionCourante = listeQuestions.get(indexQuestionCourante);

        if (reponseChoisie == questionCourante.getIndexBonneReponse()) {
            lblFeedback.setText("Bonne réponse !!!");
            score++;
        } else {
            lblFeedback.setText("Mauvaise réponse. La bonne réponse était la proposition " + questionCourante.getIndexBonneReponse() + ".");
        }
       
        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);
       
        QuestionSuivante.setEnabled(true);
       
        lblScore.setText("Score : " + score + " / " + (indexQuestionCourante + 1));
    }
     }
     
   
