/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet_cadenas_brest;

/**
 *
 * @author eloisebrest
 */
public class fenêtre_cadenas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(fenêtre_cadenas.class.getName());
    
    private Cadenas jeu;
    private int[] propositionActuelle = {0, 0, 0, 0};

    public fenêtre_cadenas() {
        initComponents();
        jeu = new Cadenas();
        mettreAJourAffichage();
    }

    private void modifierProposition(int index, int delta) {
        if (jeu == null) return;
        if (jeu.estPartieTerminee()) return;

        propositionActuelle[index] = (propositionActuelle[index] + delta + 10) % 10;
        mettreAJourAffichage();
    }

    private void mettreAJourAffichage() {

        texte_chiffre_1.setText(Integer.toString(propositionActuelle[0]));
        texte_chiffre_2.setText(Integer.toString(propositionActuelle[1]));
        texte_chiffre_3.setText(Integer.toString(propositionActuelle[2]));
        texte_chiffre_4.setText(Integer.toString(propositionActuelle[3]));

        texte_nb_chiffres_exacts.setText(Integer.toString((int) jeu.getnbExacts()));
        texte_nb_chiffres_hauts.setText(Integer.toString((int) jeu.getnbTropHauts()));
        texte_nb_chiffres_bas.setText(Integer.toString((int) jeu.getnbTropBas()));

        texte_score.setText(
                jeu.gettentativeActuelle() + " sur " + jeu.getmaxTentatives()
        );

        bouton_tester.setEnabled(!jeu.estPartieTerminee());
    }
    
    private void changerCouleurCases(java.awt.Color couleur) {
    texte_chiffre_1.setOpaque(true);
    texte_chiffre_2.setOpaque(true);
    texte_chiffre_3.setOpaque(true);
    texte_chiffre_4.setOpaque(true);

    texte_chiffre_1.setBackground(couleur);
    texte_chiffre_2.setBackground(couleur);
    texte_chiffre_3.setBackground(couleur);
    texte_chiffre_4.setBackground(couleur);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        texte_intro = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        texte_chiffre_4 = new javax.swing.JLabel();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_hauts = new javax.swing.JLabel();
        texte_nb_chiffres_hauts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_tentative = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        texte_recommencer = new javax.swing.JButton();
        affichage_resultat = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setFont(new java.awt.Font("KoHo", 1, 18)); // NOI18N
        texte_intro.setForeground(new java.awt.Color(0, 102, 51));
        texte_intro.setText("Trouve le bon code en moins de 5 tentatives !");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 6, -1, -1));

        up_chiffre_1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        up_chiffre_1.setForeground(new java.awt.Color(0, 204, 0));
        up_chiffre_1.setText("/\\");
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });
            getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 48, -1, -1));

            up_chiffre_2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
            up_chiffre_2.setForeground(new java.awt.Color(0, 204, 0));
            up_chiffre_2.setText("/\\");
                up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre_2ActionPerformed(evt);
                    }
                });
                getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 48, -1, -1));

                up_chiffre_3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
                up_chiffre_3.setForeground(new java.awt.Color(0, 204, 0));
                up_chiffre_3.setText("/\\");
                    up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 48, -1, -1));

                    up_chiffre_4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
                    up_chiffre_4.setForeground(new java.awt.Color(0, 204, 0));
                    up_chiffre_4.setText(" /\\");
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 48, -1, -1));

                        texte_chiffre_1.setFont(new java.awt.Font("KoHo", 1, 18)); // NOI18N
                        texte_chiffre_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_1.setText("0");
                        texte_chiffre_1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 1, true));
                        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 83, 72, 74));

                        texte_chiffre_2.setFont(new java.awt.Font("KoHo", 1, 18)); // NOI18N
                        texte_chiffre_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_2.setText("0");
                        texte_chiffre_2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 1, true));
                        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 83, 72, 74));

                        texte_chiffre_3.setFont(new java.awt.Font("KoHo", 1, 18)); // NOI18N
                        texte_chiffre_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_3.setText("0");
                        texte_chiffre_3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 1, true));
                        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 83, 72, 74));

                        texte_chiffre_4.setFont(new java.awt.Font("KoHo", 1, 18)); // NOI18N
                        texte_chiffre_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_4.setText("0");
                        texte_chiffre_4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 1, true));
                        getContentPane().add(texte_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 83, 72, 74));

                        down_chiffre_1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
                        down_chiffre_1.setForeground(new java.awt.Color(0, 153, 0));
                        down_chiffre_1.setText("\\/");
                        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 160, -1, -1));

                        down_chiffre_2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
                        down_chiffre_2.setForeground(new java.awt.Color(0, 153, 0));
                        down_chiffre_2.setText("\\/");
                        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 160, -1, -1));

                        down_chiffre_3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
                        down_chiffre_3.setForeground(new java.awt.Color(0, 153, 0));
                        down_chiffre_3.setText("\\/");
                        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 160, -1, -1));

                        down_chiffre_4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
                        down_chiffre_4.setForeground(new java.awt.Color(0, 153, 0));
                        down_chiffre_4.setText("\\/");
                        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 160, -1, -1));

                        bouton_tester.setFont(new java.awt.Font("KoHo", 1, 14)); // NOI18N
                        bouton_tester.setForeground(new java.awt.Color(0, 102, 51));
                        bouton_tester.setText("TESTER");
                        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_testerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 201, 89, -1));

                        texte_lbl_nb_chiffres_exacts.setFont(new java.awt.Font("KoHo", 0, 14)); // NOI18N
                        texte_lbl_nb_chiffres_exacts.setForeground(new java.awt.Color(51, 102, 0));
                        texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exacts :");
                        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 247, 171, -1));

                        texte_nb_chiffres_exacts.setForeground(new java.awt.Color(51, 102, 0));
                        texte_nb_chiffres_exacts.setText("0");
                        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

                        texte_lbl_nb_chiffres_hauts.setFont(new java.awt.Font("KoHo", 0, 14)); // NOI18N
                        texte_lbl_nb_chiffres_hauts.setForeground(new java.awt.Color(0, 204, 0));
                        texte_lbl_nb_chiffres_hauts.setText("Nombre de chiffres trop hauts :");
                        getContentPane().add(texte_lbl_nb_chiffres_hauts, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 278, -1, -1));

                        texte_nb_chiffres_hauts.setForeground(new java.awt.Color(0, 204, 0));
                        texte_nb_chiffres_hauts.setText("0");
                        getContentPane().add(texte_nb_chiffres_hauts, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 278, -1, -1));

                        texte_lbl_nb_chiffres_bas.setFont(new java.awt.Font("KoHo", 0, 14)); // NOI18N
                        texte_lbl_nb_chiffres_bas.setForeground(new java.awt.Color(0, 153, 0));
                        texte_lbl_nb_chiffres_bas.setText("Nombre de chiffres trop bas :");
                        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 308, -1, -1));

                        texte_nb_chiffres_bas.setForeground(new java.awt.Color(0, 153, 0));
                        texte_nb_chiffres_bas.setText("0");
                        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 310, -1, -1));

                        texte_tentative.setFont(new java.awt.Font("KoHo", 1, 14)); // NOI18N
                        texte_tentative.setText("Tentative");
                        getContentPane().add(texte_tentative, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 247, -1, -1));

                        texte_score.setFont(new java.awt.Font("KoHo", 1, 18)); // NOI18N
                        texte_score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_score.setText("0");
                        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 278, 96, -1));

                        texte_recommencer.setFont(new java.awt.Font("KoHo", 1, 14)); // NOI18N
                        texte_recommencer.setForeground(new java.awt.Color(51, 102, 0));
                        texte_recommencer.setText("Recommencer");
                        texte_recommencer.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                texte_recommencerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(texte_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));
                        getContentPane().add(affichage_resultat, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 334, 290, 20));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        modifierProposition(0, +1);
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        modifierProposition(1, +1);
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        modifierProposition(2, +1);
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        modifierProposition(3, +1);
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        modifierProposition(0, -1);
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        modifierProposition(1, -1);
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
        modifierProposition(2, -1);
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
        modifierProposition(3, -1);
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
        if (jeu == null) return;

    jeu.soumettreProposition(propositionActuelle.clone());
    mettreAJourAffichage();

    if (jeu.estPartieGagnee()) {
        affichage_resultat.setText(
            "VICTOIRE ! Trouvé en " + jeu.gettentativeActuelle() + " tentatives."
        );
        changerCouleurCases(java.awt.Color.GREEN);

    } else if (jeu.estPartieTerminee()) {
        affichage_resultat.setText(
            "DEFAITE. Le code secret était : " + jeu.getCodeSecretEnChaine()
        );
        changerCouleurCases(java.awt.Color.RED);

    } else {
        affichage_resultat.setText("");
    }
    }//GEN-LAST:event_bouton_testerActionPerformed

    private void texte_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texte_recommencerActionPerformed
        if (jeu == null) {
            jeu = new Cadenas();
        } else {
            jeu.genererCodeSecret();
        }
        propositionActuelle = new int[]{0, 0, 0, 0};
        affichage_resultat.setText("");
        changerCouleurCases(java.awt.Color.WHITE);
        mettreAJourAffichage();
        
    }//GEN-LAST:event_texte_recommencerActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new fenêtre_cadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel affichage_resultat;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_chiffre_4;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_hauts;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_hauts;
    private javax.swing.JButton texte_recommencer;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentative;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
